// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: replication/vsrproto/vsr.proto

package vsrproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MPropose       MessageType = 0
	MessageType_MProposeReject MessageType = 1
	MessageType_MPrepare       MessageType = 2
	MessageType_MPrepareOK     MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MPropose",
		1: "MProposeReject",
		2: "MPrepare",
		3: "MPrepareOK",
	}
	MessageType_value = map[string]int32{
		"MPropose":       0,
		"MProposeReject": 1,
		"MPrepare":       2,
		"MPrepareOK":     3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_replication_vsrproto_vsr_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_replication_vsrproto_vsr_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{0}
}

type Propose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID       uint64 `protobuf:"varint,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	Operation      []byte `protobuf:"bytes,3,opt,name=Operation,proto3" json:"Operation,omitempty"`
}

func (x *Propose) Reset() {
	*x = Propose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replication_vsrproto_vsr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propose) ProtoMessage() {}

func (x *Propose) ProtoReflect() protoreflect.Message {
	mi := &file_replication_vsrproto_vsr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propose.ProtoReflect.Descriptor instead.
func (*Propose) Descriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{0}
}

func (x *Propose) GetClientID() uint64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *Propose) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Propose) GetOperation() []byte {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ProposeReject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID       uint64 `protobuf:"varint,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,2,opt,name=SequenceNumber,proto3" json:"SequenceNumber,omitempty"`
	Reason         string `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *ProposeReject) Reset() {
	*x = ProposeReject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replication_vsrproto_vsr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposeReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeReject) ProtoMessage() {}

func (x *ProposeReject) ProtoReflect() protoreflect.Message {
	mi := &file_replication_vsrproto_vsr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeReject.ProtoReflect.Descriptor instead.
func (*ProposeReject) Descriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeReject) GetClientID() uint64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *ProposeReject) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ProposeReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Prepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewNumber      uint64   `protobuf:"varint,1,opt,name=ViewNumber,proto3" json:"ViewNumber,omitempty"`
	OperationNumber uint64   `protobuf:"varint,2,opt,name=OperationNumber,proto3" json:"OperationNumber,omitempty"`
	Propose         *Propose `protobuf:"bytes,3,opt,name=Propose,proto3" json:"Propose,omitempty"`
	CommitNumber    uint64   `protobuf:"varint,4,opt,name=CommitNumber,proto3" json:"CommitNumber,omitempty"`
}

func (x *Prepare) Reset() {
	*x = Prepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replication_vsrproto_vsr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prepare) ProtoMessage() {}

func (x *Prepare) ProtoReflect() protoreflect.Message {
	mi := &file_replication_vsrproto_vsr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prepare.ProtoReflect.Descriptor instead.
func (*Prepare) Descriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{2}
}

func (x *Prepare) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *Prepare) GetOperationNumber() uint64 {
	if x != nil {
		return x.OperationNumber
	}
	return 0
}

func (x *Prepare) GetPropose() *Propose {
	if x != nil {
		return x.Propose
	}
	return nil
}

func (x *Prepare) GetCommitNumber() uint64 {
	if x != nil {
		return x.CommitNumber
	}
	return 0
}

type PrepareOK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ViewNumber      uint64 `protobuf:"varint,1,opt,name=ViewNumber,proto3" json:"ViewNumber,omitempty"`
	OperationNumber uint64 `protobuf:"varint,2,opt,name=OperationNumber,proto3" json:"OperationNumber,omitempty"`
	CommitNumber    uint64 `protobuf:"varint,3,opt,name=CommitNumber,proto3" json:"CommitNumber,omitempty"`
}

func (x *PrepareOK) Reset() {
	*x = PrepareOK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replication_vsrproto_vsr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareOK) ProtoMessage() {}

func (x *PrepareOK) ProtoReflect() protoreflect.Message {
	mi := &file_replication_vsrproto_vsr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareOK.ProtoReflect.Descriptor instead.
func (*PrepareOK) Descriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareOK) GetViewNumber() uint64 {
	if x != nil {
		return x.ViewNumber
	}
	return 0
}

func (x *PrepareOK) GetOperationNumber() uint64 {
	if x != nil {
		return x.OperationNumber
	}
	return 0
}

func (x *PrepareOK) GetCommitNumber() uint64 {
	if x != nil {
		return x.CommitNumber
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupID       uint64         `protobuf:"varint,5,opt,name=GroupID,proto3" json:"GroupID,omitempty"`
	Source        uint64         `protobuf:"varint,10,opt,name=Source,proto3" json:"Source,omitempty"`
	Type          MessageType    `protobuf:"varint,20,opt,name=Type,proto3,enum=vsrproto.MessageType" json:"Type,omitempty"`
	Propose       *Propose       `protobuf:"bytes,30,opt,name=Propose,proto3,oneof" json:"Propose,omitempty"`
	ProposeReject *ProposeReject `protobuf:"bytes,31,opt,name=ProposeReject,proto3,oneof" json:"ProposeReject,omitempty"`
	Prepare       *Prepare       `protobuf:"bytes,32,opt,name=Prepare,proto3,oneof" json:"Prepare,omitempty"`
	PrepareOK     *PrepareOK     `protobuf:"bytes,33,opt,name=PrepareOK,proto3,oneof" json:"PrepareOK,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replication_vsrproto_vsr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_replication_vsrproto_vsr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_replication_vsrproto_vsr_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetGroupID() uint64 {
	if x != nil {
		return x.GroupID
	}
	return 0
}

func (x *Message) GetSource() uint64 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MPropose
}

func (x *Message) GetPropose() *Propose {
	if x != nil {
		return x.Propose
	}
	return nil
}

func (x *Message) GetProposeReject() *ProposeReject {
	if x != nil {
		return x.ProposeReject
	}
	return nil
}

func (x *Message) GetPrepare() *Prepare {
	if x != nil {
		return x.Prepare
	}
	return nil
}

func (x *Message) GetPrepareOK() *PrepareOK {
	if x != nil {
		return x.PrepareOK
	}
	return nil
}

var File_replication_vsrproto_vsr_proto protoreflect.FileDescriptor

var file_replication_vsrproto_vsr_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x73,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x73, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x76, 0x73, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6b, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0xa4, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x28, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x73,
	0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x07,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x79, 0x0a, 0x09, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x4b, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x69, 0x65, 0x77,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x56, 0x69,
	0x65, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xfe, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x14, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x76, 0x73, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x30, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x76, 0x73, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x88, 0x01,
	0x01, 0x12, 0x42, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x73, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x48, 0x01, 0x52, 0x0d, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x18, 0x20, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x73, 0x72, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x48, 0x02, 0x52, 0x07, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x36, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x4f, 0x4b, 0x18, 0x21, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x73, 0x72,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x4b, 0x48,
	0x03, 0x52, 0x09, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x4b, 0x88, 0x01, 0x01, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x50, 0x72,
	0x65, 0x70, 0x61, 0x72, 0x65, 0x4f, 0x4b, 0x2a, 0x4d, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x50, 0x72, 0x65,
	0x70, 0x61, 0x72, 0x65, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x50, 0x72, 0x65, 0x70, 0x61,
	0x72, 0x65, 0x4f, 0x4b, 0x10, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x76, 0x38, 0x2e, 0x72, 0x75, 0x6e,
	0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x73, 0x72, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replication_vsrproto_vsr_proto_rawDescOnce sync.Once
	file_replication_vsrproto_vsr_proto_rawDescData = file_replication_vsrproto_vsr_proto_rawDesc
)

func file_replication_vsrproto_vsr_proto_rawDescGZIP() []byte {
	file_replication_vsrproto_vsr_proto_rawDescOnce.Do(func() {
		file_replication_vsrproto_vsr_proto_rawDescData = protoimpl.X.CompressGZIP(file_replication_vsrproto_vsr_proto_rawDescData)
	})
	return file_replication_vsrproto_vsr_proto_rawDescData
}

var file_replication_vsrproto_vsr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_replication_vsrproto_vsr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_replication_vsrproto_vsr_proto_goTypes = []interface{}{
	(MessageType)(0),      // 0: vsrproto.MessageType
	(*Propose)(nil),       // 1: vsrproto.Propose
	(*ProposeReject)(nil), // 2: vsrproto.ProposeReject
	(*Prepare)(nil),       // 3: vsrproto.Prepare
	(*PrepareOK)(nil),     // 4: vsrproto.PrepareOK
	(*Message)(nil),       // 5: vsrproto.Message
}
var file_replication_vsrproto_vsr_proto_depIdxs = []int32{
	1, // 0: vsrproto.Prepare.Propose:type_name -> vsrproto.Propose
	0, // 1: vsrproto.Message.Type:type_name -> vsrproto.MessageType
	1, // 2: vsrproto.Message.Propose:type_name -> vsrproto.Propose
	2, // 3: vsrproto.Message.ProposeReject:type_name -> vsrproto.ProposeReject
	3, // 4: vsrproto.Message.Prepare:type_name -> vsrproto.Prepare
	4, // 5: vsrproto.Message.PrepareOK:type_name -> vsrproto.PrepareOK
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_replication_vsrproto_vsr_proto_init() }
func file_replication_vsrproto_vsr_proto_init() {
	if File_replication_vsrproto_vsr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_replication_vsrproto_vsr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replication_vsrproto_vsr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposeReject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replication_vsrproto_vsr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replication_vsrproto_vsr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareOK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replication_vsrproto_vsr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_replication_vsrproto_vsr_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replication_vsrproto_vsr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replication_vsrproto_vsr_proto_goTypes,
		DependencyIndexes: file_replication_vsrproto_vsr_proto_depIdxs,
		EnumInfos:         file_replication_vsrproto_vsr_proto_enumTypes,
		MessageInfos:      file_replication_vsrproto_vsr_proto_msgTypes,
	}.Build()
	File_replication_vsrproto_vsr_proto = out.File
	file_replication_vsrproto_vsr_proto_rawDesc = nil
	file_replication_vsrproto_vsr_proto_goTypes = nil
	file_replication_vsrproto_vsr_proto_depIdxs = nil
}
